# Connexion MySQL
hibernate.connection.driver_class=com.mysql.cj.jdbc.Driver
hibernate.connection.url=jdbc:mysql://localhost:3306/gestion_projet
hibernate.connection.username=root
hibernate.connection.password=

# Dialecte Hibernate
hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Options
hibernate.show_sql=true
hibernate.hbm2ddl.auto=update